name: Check of Svelte errors using `npm run check`

on: [push, pull_request]

jobs:
  check_svelte:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm run check
